apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
   name: messaging-dev
spec:
  project: default
  source:
    repoURL: 'git@github.com:Yasmaa/shippy.git'
    path: kube/messaging
    targetRevision: HEAD
    directory:
      recurse: true
      jsonnet: {}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: rabbits
  syncPolicy:
    automated: {}
