apiVersion: v1
kind: Namespace
metadata:
  name: rabbits
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    istio-injection: enabled
---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: istio-system
#   labels:
#     istio-injection: enabled
