apiVersion: v1
kind: Secret
metadata:
  name: argocd-deploy-secret
  namespace: argocd
type: Opaque
data:
  privateKey: LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUFNd0FBQUF0emMyZ3RaVwpReU5UVXhPUUFBQUNEQ1dxSEFtY2pvd29PN3crRktabWlQUjZ2TW5RZHV0QkpKUzBUSUVRZWkzZ0FBQUpEck1KY0g2ekNYCkJ3QUFBQXR6YzJndFpXUXlOVFV4T1FBQUFDRENXcUhBbWNqb3dvTzd3K0ZLWm1pUFI2dk1uUWR1dEJKSlMwVElFUWVpM2cKQUFBRUR1OXlHUUlvS2hVaXV3LzRrVzlRTXlzd0Q4Nzd3ekxDUGxHcnUzeFBBREpzSmFvY0NaeU9qQ2c3dkQ0VXBtYUk5SApxOHlkQjI2MEVrbExSTWdSQjZMZUFBQUFCbUZ5WjI5alpBRUNBd1FGQmdjPQotLS0tLUVORCBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0K